language: objective-c
osx_image: xcode611

#xcode_project: DiffableArray.xcodeproj
#xcode_scheme: DiffableArray
#xcode_sdk: 'iphonesimulator'


before_install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- set -o pipefail
- xcodebuild -project DiffableArray.xcodeproj -scheme DiffableArray -destination 'platform=iOS Simulator,OS=8.1,name=iPhone 6' test | xcpretty -c
- pod lib lint --quick
