language: objective-c
osx_image: xcode7.1

script:
- set -o pipefail
- xcodebuild -project DiffableArray.xcodeproj -scheme DiffableArray test -sdk iphonesimulator9.1 -destination "platform=iOS Simulator,name=iPhone 6" | xcpretty -c
- pod lib lint --quick

after_success:
- bash <(curl -s https://codecov.io/bash)